### ISSUE TITLE
Security vulnerabilities found

### ISSUE THREAD

**Issue by romanblachman** [SecureAuthCorp/saidp-sdk-java#102]
Hello,

It appears that the dependencies that the library is using are out-of-date.

![image](https://user-images.githubusercontent.com/5787391/108629255-c033b600-7467-11eb-9b04-d5ae82829368.png)

![image](https://user-images.githubusercontent.com/5787391/108629284-d93c6700-7467-11eb-8197-7decc46b6e7c.png)

Can you please update them?

Thank you,
Roman

**Comment by glacuesta-sa** [comment]
This will be addressed on RAD-780 next version.
