### ISSUE TITLE
validateUserPin call  always returns pin "INVALID"

### ISSUE THREAD

**Issue by nikned** [SecureAuthCorp/saidp-sdk-java#38]
@sa-rrowcliffe 
validateUserPin  call always returns pin as invalid even providing right pin value 

scenario:
step1: deliverAdHocOTPByPhone ==> (userid , phoneNumber) ==> 
{
  "status": "valid",
  "message": "",
  "user_id": "userid",
  "otp": 495723
}

step 2: validateOTP (userid, 495723) ==>
{
  "status": "invalid",
  "message": "PIN is invalid."
}

Note : this is happening with v1.0.1 and later API versions

**Comment by sa-rrowcliffe** [comment]
@nikned Did you configure https://docs.secureauth.com/display/91docs/Validate+OTP+Authentication+API+Guide#expand-ConfigurationSteps 

The IDP needs to be configured to store the OTP to leverage the Validate function.

**Comment by nikned** [comment]
@sa-rrowcliffe , yes IDP is been configured the way described in api guide . Earlier i tried with adhoc calls and our secureAuth support said that for adhoc calls , IDP doesnt store OTP, only normal sms/email/phone does . Even doing sms/email/phone api calls i see the same invalid response returned

**Comment by sa-rrowcliffe** [comment]
Hi @nikned I just tested the endpoint call from the SDK and was getting valid responses. 
When you execute the delivery of SMS, Voice or Email. You should be getting a 0 response from IDP 
This requires an input of the delivered OTP for validation. 
Can you share your Validation Code Snippet?

**Comment by nikned** [comment]
@sa-rrowcliffe  , i cross checked on IDP , the config which you have provided in the link was missing , after adding it in , i see validate is working as expected. Thanks a bunch.
